# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Phillip Kriegel
email: philkrie@gmail.com
description: Mobile Specialist @ Google
logo: "/assets/images/logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.phillipkriegel.com" # the base hostname & protocol for your site
paginate: 5 # The number of posts to show per page on your homepage

name: 'Phillip Kriegel'
bio: Super speedy sites
author_image: "/assets/images/author.jpg"
github_username:  philkrie

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate